#!/bin/bash
# Sample script for watching and maintaining an SSH tunnel with Bandicoot

readonly -a ARGS=("$@")

# Workaround corrupted socket bug ... need a better solution
if [ -f bandicoot_socket ] ; then
	rm -f bandicoot_socket
fi

while :; 
	do
	clear
  	bandicoot $ARGS 2> ./bandicoot.log
	sleep 5
done
